### PR TITLE
Add Serilog for logging

### PR DESCRIPTION
**Pull request by Azizi-Code**

### CODE REVIEW

**Review by mohammadKarimi — CHANGES_REQUESTED** [review]
Please Use ILogger in Exceptions handler. 
we usually do not need to use it in controller.

**Comment by Azizi-Code** [comment]
@mohammadKarimi => using logger in GlobalExceptionHandler instead of BaseController.

**Comment by Azizi-Code** [comment]
> Please Use ILogger in the Exceptions handler. we usually do not need to use it in controller.


@mohammadKarimi => using logger in GlobalExceptionHandler instead of BaseController. Please review it again.

**Review by mohammadKarimi — APPROVED** [review]
Perfect

**Pull request merged**
